### ISSUE TITLE
Time Tracking sync error

### ISSUE THREAD

**Issue by millsoft** [jk1/youtrack-idea-plugin#36] opened 2016-10-13 16:51 UTC
Hi,

I just installed the plugin connected with my youtrack installation and it seems to work.
I also activated the time tracker in phpstorm to track the times.

When I click on "Post work item to bugtracker" button (that rectangle with green top arrow) I get an error:
![Exhibit 1](http://i.imgur.com/1H5coKL.jpg)

The german parts translated says:
Unknown command: Type, Date or Time range of the task required: Today 0d 0h 1m

Is your plugin not working with the time track function or am I doing something wrong?

**Comment by jk1** [comment] 2016-10-13 17:17
Thank you for reporting it.
Strictly speaking time tracking feature is a part of "Task Management" IDE plugin by JetBrains. Still, I have a guess about the root cause. Which language (locale) does your YouTrack server use? Is it German?

**Comment by millsoft** [comment] 2016-10-13 17:44
yes, it is set to German. I just set the language to english in youtrack and now the plugin works! :) No errors, time is sent back to youtrack. Thanks!

I would be fine with that but one coworker doesn't speak english well :/ . I will check your code and try to make it also work with German youtrack locale.

**Comment by jk1** [comment] 2016-10-13 17:54
I guess here's the line to blame: https://github.com/JetBrains/intellij-community/blob/b1e4351dea8ddad327479c4a0e4da00380af8a99/plugins/tasks/tasks-core/src/com/intellij/tasks/youtrack/YouTrackRepository.java#L348

"Today" is not recognized by a translated YouTrack server. For German it expects "Heute" instead.

**Comment by jk1** [comment] 2016-10-14 18:19
I've contacted responsible people at JetBrains and was told this bug is to be fixed in YouTrack 7.0.

**Closed by jk1** 2016-10-14 18:19 UTC
