### ISSUE TITLE
Stacktrace: "Project (Disposed) xxx has already been disposed"

### ISSUE THREAD

**Issue by AndrePek** [jk1/youtrack-idea-plugin#67] opened 2017-07-20 12:37 UTC
Error message: 
Sorry but parent: Project (Disposed) bridge has already been disposed (see the cause for stacktrace) so the child: null 802709717: running=false; canceled=false; task=null will never be disposed

Details:
I have recently been having a problem with the Task window where, when I click Open Task, the list window flashes up and then immediately closes again. This repeats if I do it again. The only reliable way to get the Task list to open and stay open, is to either close Idea and restart it, or to File | Close Project and then reopen that.

A short while before this error I did the File | Close Project and reopen, because of the Open Task problem. Then while I was scrolling through a Git Compare with branch, this error came up. I have now added "com.github.jk1"to the Debug Log Settings, so I will have better info the next time the Task Window problem occurs.

Environment:
IntelliJ IDEA 2017.2 (although it has happened on previous versions/builds, so I don't think it is particular to this version/build)
Build #IU-172.3317.76, built on July 15, 2017
Licensed to Nightsbridge / Andre Pekelaar
Subscription is active until January 12, 2018
JRE: 1.8.0_152-release-915-b5 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.4.0-83-generic (Ubuntu 16.04.2 LTS)

Stacktrace:
Sorry but parent: Project (Disposed) bridge has already been disposed (see the cause for stacktrace) so the child: null 802709717: running=false; canceled=false; task=null will never be disposed
com.intellij.util.IncorrectOperationException: Sorry but parent: Project (Disposed) bridge has already been disposed (see the cause for stacktrace) so the child: null 802709717: running=false; canceled=false; task=null will never be disposed
	at com.intellij.openapi.util.objectTree.ObjectTree.register(ObjectTree.java:66)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:97)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:93)
	at com.intellij.openapi.progress.util.ProgressWindow.<init>(ProgressWindow.java:125)
	at com.intellij.openapi.progress.util.ProgressWindow.<init>(ProgressWindow.java:84)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:63)
	at com.intellij.openapi.progress.impl.BackgroundableProcessIndicator.<init>(BackgroundableProcessIndicator.java:44)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressAsynchronously(ProgressManagerImpl.java:139)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:341)
	at com.intellij.openapi.progress.impl.CoreProgressManager.run(CoreProgressManager.java:325)
	at com.intellij.openapi.progress.Task.queue(Task.java:115)
	at com.github.jk1.ytplugin.issues.IssueStore.update(IssueStore.kt:21)
	at com.github.jk1.ytplugin.issues.IssueStoreUpdaterComponent$initComponent$1$1.run(IssueStoreUpdaterComponent.kt:28)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by AndrePek** [comment] 2017-07-24 16:15
I think this may be the same basic issue as https://github.com/jk1/youtrack-idea-plugin/issues/64, but perhaps in a slightly different context. Certainly, the stacktraces are almost identical, across 30 lines of stacktrace

**Comment by jk1** [comment] 2017-07-24 16:42
I believe you're right and this is indeed the same issue. I can't reproduce it though and that is why it's been here for a while.

**Comment by jk1** [comment] 2017-07-25 06:33
Fixed in 0.7.1

**Closed by jk1** 2017-07-25 06:33 UTC
