### ISSUE TITLE
Time tracking is not tracking always in automatic mode 

### ISSUE THREAD

**Issue by sergyu91ma** [jk1/youtrack-idea-plugin#159] opened 2021-02-09 13:41 UTC
Hi,

I have time tracking in automatic mode and set to track for a issue.
Everything works normal when I open the issue, but after I close the IDE and start it again without opening the youtrack window the time is not tracked anymore. 
So when I look to see how much time is tracked it's actually 0 and only then it's starting to track.  

I have
PhpStorm 2020.3.2
Build #PS-203.7148.74, built on January 27, 2021 
Runtime version: 11.0.9.1+11-b1145.77 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
and youtrack integration 1.1.3

**Comment by sergyu91ma** [comment] 2021-03-14 10:37
Anyone, anything?
When it will be fixed? 
It's really annoying.

**Comment by lesslyrics** [comment] 2021-03-14 10:54
@sergyu91ma thank you for your feedback and patience, we investigate this issue and will do our best to fix it as soon as possible. Can you please also clarify a bit what do you mean by "when I look to see how much time is tracked it's actually 0"? And in the configuration dialog, did you also untick the "automatically create work item when closing the project"? 
![image](https://user-images.githubusercontent.com/42976128/111065822-bfbd9680-84cc-11eb-9efd-1c43047cc969.png)

**Comment by sergyu91ma** [comment] 2021-03-14 12:51
Hello,

Here are my settings: 
![image](https://user-images.githubusercontent.com/6949205/111068789-e1ba1780-84d2-11eb-97d9-a56463f4cb80.png)

So to clarify: 
1. Open PHPStorm
2. There is already an work item opened from previous working sessions
3. Don't open youtrack window (it's minimized) 
![image](https://user-images.githubusercontent.com/6949205/111068930-62791380-84d3-11eb-8e7f-1df4ce7a3e2f.png)
4. Let some time to pass (eg. 5 min) and just work normally with the code. 
5. Open youtrack window and check tracked time 
![image](https://user-images.githubusercontent.com/6949205/111069128-4de94b00-84d4-11eb-8e21-1064970a0934.png)
6. We see that only now it's starting to track time and those 5 min or the time before opening the Youtrack window are gone and untracked. 
7. Normally it should track as soon as I open PHPStorm if an work item is opened. 

Let me know if you need anything else. 

Thanks.

**Comment by lesslyrics** [comment] 2021-03-15 09:23
@sergyu91ma thanks a lot for the clarifications. Your IDEA log (Help -> Show log in files -> Idea.log) would really help because so far I cannot reproduce this issue in the completely same environment. You could also update your version to 1.1.4 and also you should be able to see this part even if YouTrack tab is minimized, so please let us know if it is not like that. 
![image](https://user-images.githubusercontent.com/42976128/111130993-df19f980-8588-11eb-905b-5023c009b61a.png)

**Comment by sergyu91ma** [comment] 2021-03-15 09:34
Hi,
I am on 1.1.4 since it got released. 
![image](https://user-images.githubusercontent.com/6949205/111131985-7da25c80-8581-11eb-9c9c-bd507ce7f377.png)

So I opend PHPstorm, I have an work item opened from previous work session, but as you can see in the image Youtrack is not tracking: 
![image](https://user-images.githubusercontent.com/6949205/111132522-2486f880-8582-11eb-9943-88f86adcb855.png)

Now i clicked on the minimized Youtrack window and only now it's starting to track time. 
![image](https://user-images.githubusercontent.com/6949205/111132673-4da78900-8582-11eb-910d-b299483f7077.png)

Here is the log of what i described above: 
[idea.log](https://github.com/jk1/youtrack-idea-plugin/files/6140272/idea.log)


Thanks.

**Comment by sergyu91ma** [comment] 2021-03-24 18:26
Hello,

Did you managed to reproduce it?

**Comment by jk1** [comment] 2021-04-04 22:55
Hi @sergyu91ma 

We appreciate your patience. This bug proved to be not that easy to reproduce indeed.
Still, it all boils down to the customized IDE toolbar of yours. The issue can only occur if you remove time tracking buttons from the IDE toolbar, which perfectly explains why we have no other similar bug reports. While the permanent fix is not delivered you can add the buttons back to the toolbar as a workround.

**Comment by sergyu91ma** [comment] 2021-04-05 00:26
Hi,

Hmm, weird thing. I didn't remove any time tracking buttons by myself from the toolbar, but it's weird that it has this bug if they're not in the toolbar. 
 
I looked into adding them back but I don't know how. 

Can you show me please how it's default? Or how to add them to the toolbar? 

Thanks.

**Comment by jk1** [comment] 2021-04-05 02:34
Try restoring NavBarToolBarOthers

![image](https://user-images.githubusercontent.com/715844/113531060-6da1f980-95d0-11eb-8e63-b99565b8bb3b.png)

**Comment by sergyu91ma** [comment] 2021-04-05 11:41
Thanks for the clarifications. Indeed now it works correctly, but i have added the buttons manually. 
Even after resetting the toolbars to default  buttons from youtrack plugin weren't there. 

![image](https://user-images.githubusercontent.com/6949205/113570438-ff375880-961c-11eb-9037-db215c005fa0.png)

**Comment by jk1** [comment] 2021-04-05 14:08
Thank you for the update.
It's great to see time tracking working as expected for you.

A permanent fix to the issue will make time tracking start regardless of the toolbar configuration.

**Comment by jk1** [comment] 2021-04-08 20:27
The said fix has been included into 1.2.0

**Closed by jk1** 2021-04-08 20:27 UTC
